ARG BASEIMAGE
FROM $BASEIMAGE

ENTRYPOINT cd /opt/ml/input/data/classifier &&  \
           tar --verbose -xf model.tar.gz && \
           cd /opt/code && \
           python train.py --eval_clf=/opt/ml/input/data/classifier/best.pth --attr=Smiling
               
